# File: .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'

    - name: Install dependencies
      run: npm install
      working-directory: ./RickAndMorty

    - name: Run unit tests
      run: npm test
      working-directory: ./RickAndMorty
    
    # Iniciar el servidor Angular en segon pla
    - name: Start Angular server
      run: npm start -- --host 0.0.0.0 --disable-host-check &
      working-directory: ./RickAndMorty

    # Esperar uns segons per assegurar que el servidor està llest
    - name: Wait for Angular server
      run: |
        echo "Waiting for the server to start..."
        sleep 10

    # Executar els tests de Selenium
    - name: Run Selenium tests
      run: node selenium-tests/character-detail-page.spec.js
      working-directory: ./RickAndMorty

  deploy:
    runs-on: ubuntu-24.04
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'

    - name: Install dependencies
      run: npm install
      working-directory: ./RickAndMorty

    - name: Build project
      run: npm run build -- --configuration=github-pages
      working-directory: ./RickAndMorty

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./RickAndMorty/dist/RickAndMorty
